name: build
on: 
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/artefacts/build.sh unit
      # - uses: actions/upload-artifact@v1
      #   with:
      #     name: native-go-web
      #     path: ./build/native
  
  build:
    runs-on: ubuntu-18.04

    steps:
      - run: ./scripts/artefacts/build.sh package
      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@latest
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     body: |
      #       Changes in this Release
      #       - First Change
      #       - Second Change
      #     draft: false
      #     prerelease: false